/// Flutter icons MyIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData maximizar = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData produto = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adicionar = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_de_sync___download = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData localizar_exemplares = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData localizar_obras = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airline_seat_legroom_normal = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movimenta_facil = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nfc = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifica__es = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData obras = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ocultar_senha = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ordena__o_f_cil = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData prancheta_19 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inventario = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_de_sync___erro = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_de_sync___pronto = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status_de_sync___upload = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sync_icon = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salvar = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarme = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audit_veis = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cadastro_facil = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c_digo_de_barras = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colunas = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contagem_facil = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData detalhamento_facil = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editar = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email___cone_de_user_na_tela_de_login_ = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empr_stimo_e_devolu__o = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData excluir = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exemplares = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exportar = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fechar = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filiais = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filtros = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData localiza__es = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData _cone_de_modelo_de_csv_para_importa__o__recurso_dispon_vel_em_app_v2_rfidfacil_com_na_parte_de_itens = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData informa__es = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData localiza__es_1 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movimenta_facil_1 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData obras_1 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData portais = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData relatorios = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cadastramento = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empr_stimo_devolu__o = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exemplares_1 = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gest_o_de_usu_rios = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData configura__es = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grupo_de_usu_rios = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ver_senha = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData _cone_de_importar_csv = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData produto_1 = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData itens = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData container = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cargas = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airline_seat_legroom_reduced = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airline_seat_recline_extra = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData petroleo__1_ = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pdv_3 = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broken_bottle = IconData(0xe948, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_up = IconData(0xf139, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_circle_down = IconData(0xf13a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData anchor = IconData(0xf13d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_alt = IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullseye = IconData(0xf140, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_numeric_down = IconData(0xf162, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sort_numeric_up = IconData(0xf163, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xf182, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xf183, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive = IconData(0xf187, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taxi = IconData(0xf1ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tree = IconData(0xf1bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData database = IconData(0xf1c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_notch = IconData(0xf1ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData birthday_cake = IconData(0xf1fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_area = IconData(0xf1fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie = IconData(0xf200, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_line = IconData(0xf201, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_secret = IconData(0xf21b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData transgender_alt = IconData(0xf225, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus_double = IconData(0xf226, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData venus_mars = IconData(0xf228, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mars_stroke = IconData(0xf229, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mouse_pointer = IconData(0xf245, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i_cursor = IconData(0xf246, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_start = IconData(0xf251, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_half = IconData(0xf252, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assistive_listening_systems = IconData(0xf2a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData american_sign_language_interpreting = IconData(0xf2a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData low_vision = IconData(0xf2a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
